livros = ['Java', 'Sql', 'Delphi', 'Phyton']
livros.append('Android')
print(livros)
livros.insert(0, 'Oracle')
print(livros)
livros.insert(4, 'C')
print(livros)
livros.pop(3)
print(livros)
livros.remove('C')
print(livros)
livros.sort()
print(livros)
livros.reverse()
print(livros)
print(livros.count('Phyton'))